# name: Swift

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v


# name: execution2

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Force Xcode
#       run: sudo xcode-select -switch /Applications/Xcode.app
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v

name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Run tests
      run: xcodebuild clean test -project "annnimationDemo.xcodeproj" -scheme "annnimationDemo" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest"
    - name: Build App
      run: xcodebuild -project "annnimationDemo.xcodeproj" -scheme "main" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

