# name: Swift

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v

execution:

- concurrency: 50

held for 3m

ramp up: 2m

scenario: Choose Flight

scenarios:

Choose Flight: requests:

-label: blazedeno

method: GET

url: https://9141-122-170-99-65.ngrok.io

- label: reserve

method: POST

url: https://9141-122-170-99-65.ngrok.io/reserve.php

body fromPort: Paris

toPort: Buenos Aires
